# This is a basic workflow that is manually triggered

name: Scripts Linter

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        check_together: 'yes'
