name: SSH Debugging Session

on:
  workflow_dispatch:

jobs:
  ssh-debugging-dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
